version: '3.0'
services: 
        google-maps-scraper-image:
                                  container_name: google-maps-scraper-containner
                                  dockerfile: Dockerfile
            

